### PR TITLE
Add Devise

### PR DESCRIPTION
**Pull request by Fene-87**
In this milestone, I add Devise gem to my application and use it for registration and login of users.

Accomplishments:
- Remove current_user method in ApplicationController.
- Enable registration of new user.
- Enable user login by a combination of email and password.
- Hashed passwords are stored in database.
- Ask for combination of email.
- Can reset password.
- Modify the views in devise for registration and login to match the wireframes.

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Fene-87 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that requires contributions from partners of the team. Kindly ensure that your partner(s) contributes.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fene-87** [comment]
Hey @brytebee I was unpaired with my partner so I have been given the greenlight to proceed solo.

**Comment by brytebee** [comment]
@Fene-87 Sorry to hear about that. Kindly provide a screenshot of the mail that permits you to work solo.

**Comment by Fene-87** [comment]
solo-approval
Here is the conversation @brytebee

**Comment by brytebee** [comment]
Hello, @Fene-87

I would recommend you write to student success for email permission if you've not received one. If you have, kindly provide it so I can proceed to review your code.

**Comment by Fene-87** [comment]
@brytebee I don't know why you are insisting with the email stuff. You can clearly see that Bee from student success reached out on slack, she said that if the day passed I would be unpaired and you see that the guy was removed. My first reviewer approved my first pull request so I don't get why you are insisting on the email which by the way would take close to 6 hours before I get a response. That slack is prove enough. Here is a screenshot of my dashboard to make it clear I am solo.
new
Here is the email conversation as well.
email

**Comment by brytebee** [comment]
Hello @Fene-87,

Kindly note that the email you've provided only permits you to "...work on solo projects and reviewing materials for technical projects while you wait...". More so, the fact that your partner has been removed doesn't permit working on pair projects solo.

I understand that you're trying to meet the week's milestones, however, you need to do so within the rules.

Thanks.

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Fene-87 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that requires contributions from partners of the team. Kindly ensure that your partner(s) contributes.

**Kindly note that it is required that for pair programming to be reviewed with solo contributions there has to be an email permission clearly stating you should continue to work on pair-programming tasks solo.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fene-87** [comment]
@brytebee What rules and you can clearly see that I am solo. I have even proved it man. You are so fixated on too much bureaucracy that it seems to blind you from the truth. Any ways cheers man.

**Review by peterrobert — CHANGES_REQUESTED** [review]
Hi @Fene-87 , 

### INVALID 🛑 

- As the code reviewer above has said, this is a pair programming activity and you are only permitted to work on the solo project as per the email from the student success. Apologies, but I have to agree with @brytebee. Kindly only work on solo activities.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @Fene-87      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯
- [x] Blog app  devise running as intended💯 
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Pull request merged**
